services:
  db:
    image: postgres
    container_name: netumo_postgres
    env_file:
      - ./docker-compose.env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 81:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
  #   depends_on:
  #     - db

  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - ./docker-compose.env
    networks:
      - app

  backend:
    build:
      context: ./mini-netumo-api
      dockerfile: Dockerfile
      target: prod
    container_name: backend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./mini-netumo-api:/app:delegated
    #   - /app/node_modules
    env_file:
      - ./docker-compose.env
    depends_on:
      - db
      - redis
    networks:
      - app

  frontend1:
    build:
      context: ./mini-netumo-frontend
    container_name: frontend1
    networks:
      - app

  frontend2:
    build:
      context: ./mini-netumo-frontend
    container_name: frontend2
    networks:
      - app

  frontend3:
    build:
      context: ./mini-netumo-frontend
    container_name: frontend3
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      # Local HTTP port, change 8080 to 80 in production
      - "80:80"
      # HTTPS port, keep 443 as usual (adjust if needed)
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/original_certs:/etc/letsencrypt/original_certs:ro
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
      # - /home/mcharo/nginx-certs/certs/selfsigned.crt:/etc/letsencrypt/original_certs/fullchain1.pem:ro
      # - /home/mcharo/nginx-certs/certs/selfsigned.key:/etc/letsencrypt/original_certs/privkey1.pem:ro
    depends_on:
      - frontend1
      - frontend2
      - frontend3
      - backend
    networks:
      - app

volumes:
  static_files:

networks:
  app:
    driver: bridge
