version: "3.8"

services:
  db:
    image: postgres
    container_name: netumo_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my_network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - my_network

  backend:
    build:
      context: ./mini-netumo-api
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - my_network

  frontend1:
    build:
      context: ./mini-netumo-frontend
    container_name: frontend1
    networks:
      - my_network

  frontend2:
    build:
      context: ./mini-netumo-frontend
    container_name: frontend2
    networks:
      - my_network

  frontend3:
    build:
      context: ./mini-netumo-frontend
    container_name: frontend3
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      # Local HTTP port, change 8080 to 80 in production
      - "8080:8080"
      # HTTPS port, keep 443 as usual (adjust if needed)
      - "443:443"
    volumes:
      - static_files:/app/staticfiles:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - /etc/letsencrypt/original_certs:/etc/letsencrypt/original_certs:ro
      # - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      # - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
      - /home/mcharo/UDOM/2nd\ sem/CS\ 421/assignments/certs/selfsigned.crt:/etc/letsencrypt/original_certs/fullchain1.pem:ro
      - /home/mcharo/UDOM/2nd\ sem/CS\ 421/assignments/certs/selfsigned.key:/etc/letsencrypt/original_certs/privkey1.pem:ro
    depends_on:
      - frontend1
      - frontend2
      - frontend3
      - backend
    networks:
      - my_network

volumes:
  static_files:

networks:
  my_network:
    driver: bridge
