name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Deploy to EC2 via SSH with full cleanup
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          echo "Changing to app directory..."
          cd /home/ubuntu/mini-netumo-frontend

          echo "Cleaning working directory..."
          git reset --hard
          git clean -fd

          echo "Pulling latest changes..."
          git pull origin development

          echo "Stopping all containers..."
          docker stop $(docker ps -aq) || true

          echo "Removing all containers..."
          docker rm $(docker ps -aq) || true

          echo "Removing all images..."
          docker rmi -f $(docker images -aq) || true

          echo "Removing all volumes..."
          docker volume rm $(docker volume ls -q) || true

          echo "Pruning system (remove dangling images, containers, volumes)..."
          docker system prune -a --volumes -f || true

          echo "Building fresh containers..."
          docker compose --env-file docker-compose.env build --no-cache

          echo "Starting services..."
          docker compose --env-file docker-compose.env up -d

          echo "Deployment complete."
        EOF
